[tool.pytest.ini_options]
filterwarnings = [
               'ignore:Call to deprecated create function.* Create unlinked descriptors is going to go away:DeprecationWarning'
               ]
addopts = [
        "--import-mode=importlib"
        ]
