optimiser:
  name: AdamQLROptimiser
  initial_damping: 1.0
  damping_algorithm: kfac
  damping_decrease_factor: 0.95
  damping_increase_factor: 1.0526
  damping_clipping: [1e-8, null]
  curvature_matrix: hessian
  # lr_ema: 0.5
  # lr_curvature_ema: 0.5
  # saddle_free_lr_curvature: True
  lr_clipping: 0.03
