model:
  name: ResNet18
  num_classes: 10
loss:
  name: cross_entropy_loss
  num_classes: 10
dataset:
  name: CIFAR10
  normalise_inputs: True
  normalise_outputs: False
  validation_proportion: 0.1  # 5000/50000

num_epochs: 72
batch_size: 128
forward_pass_extra_kwargs: [is_training]

runs_per_gpu: 1
# max_training_time: 900  # 15 minutes
max_training_time: 3600  # 1 hour
