model:
  name: MLP
  output_sizes: [50, 10]
  activation: relu
  with_bias: True
loss:
  name: cross_entropy_loss
  num_classes: 10
dataset:
  name: FashionMNIST
  normalise_inputs: True
  normalise_outputs: False
  validation_proportion: 0.1666666667

num_epochs: 10
batch_size: 50

runs_per_gpu: 6
max_training_time: 900  # 15 minutes
