model:
  name: RosenbrockModel
  a: 1
  b: 100
  # initial_position: [1, -1]
loss:
  name: null_loss
dataset:
  name: NullDataset

num_epochs: 200
batch_size: 1

runs_per_gpu: 6
max_training_time: 900  # 15 minutes
